name: raidon_fhir
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  fhir: ^0.7.0
  fhir_us_core_extension:
    path: packages/fhir_us_core_extension
  dme_pao:
    path: packages/dme_pao
  rfa_model:
    path: packages/rfa_model
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  go_router: ^3.1.0
  google_place: ^0.4.7
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  json_annotation: ^4.5.0
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11
  fluttertoast: ^8.0.9
  flutter_secure_storage: ^5.0.2
  reactive_forms: ^13.0.0
  google_fonts: ^3.0.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mockito: ^5.2.0

flutter:
  uses-material-design: true
  assets:
    - dotenv
